FROM python:3.11

WORKDIR /app

COPY . .

ENV PYTHONPATH=/app
ENV LOG_PATH=logs

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
